config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # get 'contacts/index', as: 'contacts'
  # get 'contacts/new', as: 'new_contact'
  # post 'contacts/create', as: 'create_contact'
  # get 'contacts/:id/edit', to: 'contacts#edit', as: 'edit_contact'
  # patch 'contacts/:id/update', to: 'contacts#update', as: 'update_contact'
  # delete 'contacts/:id/destroy', to: 'contacts#destroy', as: 'destroy_contact'
  resources :contacts, except: [:show] do
      get 'autocomplete', on: :collection
  end

  root 'contacts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :group 

  paginates_per 5
  
  validates :name, :email, :group_id, presence: true
  validates :name, length: { minimum: 2 }

  has_attached_file :avatar, styles: { medium: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing-photo.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def gravatar
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end


  scope :search, -> (term) do
     where('LOWER(name) LIKE :term or 
            LOWER(company) LIKE :term or
            LOWER(email) LIKE :term', term: "%#{term.downcase}%") if term.present? 
  end
  # def self.search(term)
  #     if term && !term.empty?
  #        where('name LIKE ?', "%#{term}%")
  #     else
  #        all
  #     end 
  # end

  scope :by_group, -> (group_id) { where(group_id: group_id) if group_id.present? }  

  # def self.by_group(group_id)
  #     if group_id && !group_id.empty?
  #         where(group_id: group_id) 
  #     else
  #         all
  #     end
  # end

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :contacts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact,  only: [:edit, :update, :destroy]

  def index
      session[:selected_group_id] = params[:group_id]
      @contacts = Contact.by_group(params[:group_id]).search(params[:term]).order(created_at: :desc).page(params[:page])  
  end

  def autocomplete
    @contacts = Contact.search(params[:term]).order(created_at: :desc).page(params[:page])
    #render json: @contacts.map { |contact| { id: contact.id, value: contact.name } }
  end

  def new
    @contact = Contact.new
  end

  def create  
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Contact was successfully created"
      redirect_to contacts_path(previous_query_string)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:success] = "Contact was successfully updated."
      redirect_to contacts_path(previous_query_string)
    else 
      render 'edit'
    end
  end
  
  def destroy 
      @contact.destroy 
      flash[:success] = "Contact was successfully deleted."
      redirect_to contacts_path
  end


  private

  def contact_params  
    params.require(:contact).permit(:name, :email, :company, :address, :phone, :group_id, :avatar)
  end

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def previous_query_string
    session[:selected_group_id] ? { group_id: session[:selected_group_id] } : {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td class="middle">
    <div class="media">
      <div class="media-left">
        <a href="#">          
          <%= image_tag contact.avatar.url(:thumb), class: "media-object", style: "width:100px; height:100px" %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= contact.name %></h4>
        <address>
          <strong><%= contact.company %></strong><br>
          <%= contact.email %>
        </address>
      </div>
    </div>
  </td>
  <td width="100" class="middle">
    <div>
      <%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: 'Edit' do %>
         <i class="glyphicon glyphicon-edit"></i>
      <% end %>
      <%= link_to contact_path(contact), method: :delete, class: "btn btn-circle btn-danger btn-xs", title: 'Remove', data: { confirm: "Are you sure?" } do %>
         <i class="glyphicon glyphicon-remove"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { multipart: true }) do |f| %>

    <div class="panel-body">

        <% if @contact.errors.any? %>
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <h3>Please correct this following errors:</h3>

                        <ul>
                            <% @contact.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        <% end %>

      <div class="form-horizontal">
        <div class="row">
          <div class="col-md-8">

            <div class="form-group">
              <%= f.label :name, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :company, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :company, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :email, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :phone, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_field :phone, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :address, class: "control-label col-md-3" %>
              <div class="col-md-8">
                <%= f.text_area :address, class: "form-control", rows: 3 %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :group_id, class: "control-label col-md-3" %>
              <div class="col-md-5">
                <% attr = { prompt: "Select Group" } %>
                <% attr[:selected] = session[:selected_group_id].to_i if session[:selected_group_id] %>
                <%= f.collection_select :group_id, Group.all, :id, :name, attr,  class: "form-control" %>
              </div>
              <div class="col-md-3">
                <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
              </div>
            </div>
            <div class="form-group" id="add-new-group" style="display: none;">
              <div class="col-md-offset-3 col-md-8">
                <div class="input-group">
                  <input type="text" name="new_group" id="new_group" class="form-control">
                  <span class="input-group-btn">
                    <a href="#" class="btn btn-default">
                      <i class="glyphicon glyphicon-ok"></i>
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                 <%= image_tag @contact.avatar.url(:thumb), style: "width:150px; height:150px" %>
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div class="text-center">
                <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <%= f.submit @contact.new_record? ? "Save" : "Update", class: "btn btn-primary" %>
              <a href="#" class="btn btn-default">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <strong>Edit Contact</strong>
    </div>
    <%= render 'form' %>   
</div>

app/views/contacts/index.html.erb
<div class="panel panel-default">
  <table class="table">
      <%= render @contacts %>
  </table>
  <% if @contacts.blank? %>
   <div class="panel-footer message">
      <div class="alert alert-warning">
          <strong>Record not found</strong>
      </div>
   </div>  
<% end %> 
</div>

<div class="text-center">
  <%= paginate @contacts %>
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <strong>Add Contact</strong>
    </div>
    <form action="/contacts/create" method="post">

    <form action="/contacts/create" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="panel-body">

                <div class="row">
                    <div class="col-md-12">
                      <% if @contact.errors.any? %>
                          <div class="alert alert-danger">
                             <h3>Please correct this following errors:</h3>
                              <ul>
                                    <% @contact.errors.full_messages.each do |message| %>
                                         <li><%= message %></li>
                                     <% end %>
                              </ul>
                          </div>
                      <% end %>
                    </div>
                </div>
            
          <div class="form-horizontal">
            <div class="row">
              <div class="col-md-8">

                <div class="form-group">
                  <label for="name" class="control-label col-md-3">Name</label>
                  <div class="col-md-8">
                    <input type="text" name="contact[name]" id="name" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <label for="company" class="control-label col-md-3">Company</label>
                  <div class="col-md-8">
                    <input type="text" name="contact[company]" id="company" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <label for="email" class="control-label col-md-3">Email</label>
                  <div class="col-md-8">
                    <input type="text" name="contact[email]" id="email" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <label for="phone" class="control-label col-md-3">Phone</label>
                  <div class="col-md-8">
                    <input type="text" name="contact[phone]" id="phone" class="form-control">
                  </div>
                </div>

                <div class="form-group">
                  <label for="name" class="control-label col-md-3">Address</label>
                  <div class="col-md-8">
                    <textarea name="contact[address]" id="address" rows="3" class="form-control"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label for="group" class="control-label col-md-3">Group</label>
                  <div class="col-md-5">
                    <select name="contact[group_id]" id="group" class="form-control">
                      <option value="">Select group</option>
                      <%= Group.all.each do |group| %>
                            <option value="<%= group.id %>"><%= group.name %></option>
                      <% end %>  
                    </select>
                  </div>
                  <div class="col-md-3">
                    <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
                  </div>
                </div>
                <div class="form-group" id="add-new-group" style="display: none;">
                  <div class="col-md-offset-3 col-md-8">
                    <div class="input-group">
                      <input type="text" name="new_group" id="new_group" class="form-control">
                      <span class="input-group-btn">
                        <a href="#" class="btn btn-default">
                          <i class="glyphicon glyphicon-ok"></i>
                        </a>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="fileinput fileinput-new" data-provides="fileinput">
                  <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                    <img src="http://placehold.it/150x150" alt="Photo">
                  </div>
                  <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                  <div class="text-center">
                    <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-offset-3 col-md-6">
                  <button type="submit" class="btn btn-primary">Save</button>
                  <a href="#" class="btn btn-default">Cancel</a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </form>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}"%>
<% end %>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "My Contact", root_path , class: "navbar-brand text-uppercase" %>
        </div>
        <!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          
          <div class="nav navbar-right navbar-btn">
            <%= link_to new_contact_path, class: "btn btn-default" do %>
                <i class="glyphicon glyphicon-plus"></i>
                  Add Contact
            <% end %>
      
          </div>
          <%= render 'layouts/search_form' %>        
        </div>
      </div>
    </nav>

app/views/layouts/_search_form.html.erb
<%= form_tag(contacts_path, class: "navbar-form navbar-right", role: "search", method: :get) do %>
    <div class="input-group">
        <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search...", autocomplete: "off" %>
        <%= hidden_field_tag :group_id, params[:group_id] %>
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit" >
               <i class="glyphicon glyphicon-search"></i>
            </button>
        </span> 
    </div>
<% end %>        
      

app/views/layouts/_sidebar.html.erb
 <div class="list-group">
            <% active = (params[:group_id] == nil || params[:group_id].empty?) && !session[:selected_group_id]? 'active' : '' %>
                <%= link_to  contacts_path, class: "list-group-item #{active}" do %>
                All Contact <span class="badge"><%= Contact.count %></span>
            <% end %>
      
            <% Group.all.each do |group| %>
                <% active = params[:group_id].to_i == group.id || (session[:selected_group_id] && session[:selected_group_id].to_i == group.id) ? 'active' : '' %>
                    <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
                    <%= group.name %><span class="badge"><%= group.contacts.count  %></span>
                <% end %>
            <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <!-- navbar -->
    <%= render 'layouts/navbar'%>

    <!-- content -->
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>